# Copyright 2021 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 3600s

substitutions:
  _IMAGE_NAME: team1.task1

steps:

# After acceptance testing, changes are pushed to the master branch.
# Publish image in a notebook PROD environment for general use.
- name: gcr.io/cloud-builders/gcloud
  id: 'publish-prod-image'
  entrypoint: /bin/bash
  args: [ './publish-prod-env.sh']
  env:
  - 'LOCATION=us-central1-a'
  - 'IMAGE_NAME=${_IMAGE_NAME}'
  - 'PROJECT_ID=${PROJECT_ID}'